// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from '@prisma/config';
import * as dotenv from 'dotenv';

// قراءة المتغيرات من ملف .env
dotenv.config();

export default defineConfig({
  datasource: {
    url: process.env.DATABASE_URL as string,
  },
  migrations: {
    seed: 'npx ts-node prisma/seed.ts',
  },
});